const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "90%",
    gap: 5,
    backgroundColor: "#F8F4F0",
    borderRadius: 5,
  },
  callbackContainer: {
    width: "100%",
    gap: 10,
    position: "absolute",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    bottom: 0,
    flexDirection: "column",
    padding: 30,
    backgroundColor: "#FCFBF9",
    height: 200,
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  gap15: {
    gap: 15,
  },
  textInput: {
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#E6E1DA",
    width: 250,
    borderRadius: 10,
    textAlign: "center",
    letterSpacing: 5,
    alignSelf: "center",
    fontSize: 20,
    marginBottom: 5,
  },
  layoutContainerWithModal: {
    backgroundColor: "#EBE6DF",
    filter: "blur(3px)",
  },
  layoutContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FCFBF9",
    gap: 40,
  },
  content: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
  },
  button: {
    backgroundColor: "#E6E1DA",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    fontWeight: "bold",
    fontSize: 11,
  },
  greenButtonText: {
    fontWeight: "bold",
    color: "white",
    fontSize: 15,
  },
  greenButton: {
    borderRadius: 20,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingVertical: 10,
    backgroundColor: "#03D47C",
  },
  buttonNegative: {
    borderRadius: 20,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingVertical: 10,
    backgroundColor: "#F25730",
  },
  buttonNegativeSmall: {
    borderRadius: 20,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    width: 80,
    paddingVertical: 10,
    backgroundColor: "#F25730",
  },
  buttonTextNegative: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 11,
  },
  title: {
    fontSize: 15,
  },
  hugeText: {
    fontSize: 17,
    fontWeight: "bold",
  },
  buttonContainer: {
    flexDirection: "row",
    gap: 5,
  },
} as const;

export default styles;
